;;; Uncomment the modules you'd like to use and restart Prelude afterwards

;;; Code:

(require 'prelude-c)
;; (require 'prelude-clojure)
;; (require 'prelude-coffee)
(require 'prelude-common-lisp)
(require 'prelude-company)
(require 'prelude-css)
(require 'prelude-emacs-lisp)
(require 'prelude-erc)
;; (require 'prelude-erlang)
;; (require 'prelude-evil)
(require 'prelude-go)
;; (require 'prelude-haskell)
(require 'prelude-helm-everywhere)
(require 'prelude-helm)
(require 'prelude-ido)
(require 'prelude-js)
;; (require 'prelude-key-chord)
;; (require 'prelude-latex)
(require 'prelude-lisp)
;; (require 'prelude-mediawiki)
;; (require 'prelude-ocaml)
(require 'prelude-org)
(require 'prelude-perl)
(require 'prelude-programming)
(require 'prelude-python)
(require 'prelude-ruby)
;; (require 'prelude-scala)
;; (require 'prelude-scheme)
;; (require 'prelude-scss)
(require 'prelude-shell)
(require 'prelude-web)
(require 'prelude-xml)
(require 'prelude-yaml)

;;; prelude-modules.el ends here
